let promise  =  new promise((reject,resolev)=>{
    try{
        let 
    }
    catch((error)=>{
        console.log(error)
    })
})