let promise  =  new promise((reject,resolev)=>{
    try{

    }
    catch((error)=>{
        console.log(error)
    })
})